# Generated by Django 2.2.4 on 2019-08-27 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190827_0530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_charge_id',
        ),
    ]
