# Generated by Django 2.2.4 on 2019-08-29 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_coupon_amout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='amout',
            new_name='amount',
        ),
    ]
