# Generated by Django 2.2.4 on 2019-09-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
