# Generated by Django 2.2.4 on 2019-09-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_billingaddress_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='phone',
            field=models.CharField(max_length=21, null=True),
        ),
    ]
