# Generated by Django 2.2.4 on 2019-09-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='purchase_status',
            field=models.BooleanField(default=False),
        ),
    ]
