# Generated by Django 2.2.4 on 2019-09-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_wishlist_purchase_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='purchase_status',
        ),
    ]
