# Generated by Django 2.2.4 on 2019-09-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_wishlist_purchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='slug',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
